CREATE OR REPLACE TYPE TEMP_TYPE
(
FIRST_NAME VARCHAR2(20), 
LAST_NAME VARCHAR2(20), 
DEPART_NAME VARCHAR2(20)
)
/
CREATE OR REPLACE FUNCTION GET_EMPLOYEE
(LOCATION IN NUMBER)
RETURN TEMP_TYPE
AS 
TOTAL_RECORD TEMP_TYPE;
BEGIN
SELECT A.FIRST_NAME, A.LAST_NAME, B.DEPARTMENT_NAME INTO TOTAL_RECORD 
FROM EMPLOYEES A, DEPARTMENTS B 
WHERE A.DEPARTMENT_ID=B.DEPARTMENT_ID AND LOCATION_ID=LOCATION;
RETURN(TOTAL_RECORD ); 
END;
